DROP TABLE IF EXISTS `lucene_cmpgn_launch_dtl`;
CREATE TABLE `lucene_cmpgn_launch_dtl` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT` varchar(100) NOT NULL,--add
  `CMPGN_ID` varchar(100) NOT NULL,
  `COUNTRY_CODE` varchar(10) NOT NULL,
  `CMPGN_VALID_RCPNT_CNT` int(11) NOT NULL DEFAULT '0',
  `CMPGN_INVLD_RCPNT_CNT` int(11) NOT NULL DEFAULT '0',
  `CMPGN_PLANNED_LAUNCH_DATE` datetime DEFAULT NULL,
  `EBAY_RUN_DATE` datetime DEFAULT NULL,
  `RCPNT_LOAD_STATUS` varchar(10) NOT NULL DEFAULT 'I',--add
  `RETRY_TIMES` int(11) NOT NULL DEFAULT '0',--add
  `LAUNCH_ID` varchar(100) NOT NULL,
  `LAUNCH_RCPNT_CNT` int(11) NOT NULL DEFAULT '0',
  `LAUNCH_PERCENT` float(11,2) NOT NULL DEFAULT '0.00',
  `LAUNCH_DATE` datetime DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LAUNCH_ID` (`LAUNCH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

DROP TABLE IF EXISTS `lucene_cmpgn_user_rcpnt_dtl`;
CREATE TABLE `lucene_cmpgn_user_rcpnt_dtl` (
  `CMPGN_ID` varchar(100) NOT NULL,
  `USR_ID` varchar(100) NOT NULL,
  `LAUNCH_ID` varchar(100) NOT NULL,
  `LAUNCH_DATE_TS` datetime DEFAULT NULL,
  `LAUNCH_DATE` date DEFAULT NULL,
  KEY `LAUNCH_DATE` (`LAUNCH_DATE`),
  KEY `launch_date_ts` (`LAUNCH_DATE_TS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY HASH (DAY(LAUNCH_DATE))
PARTITIONS 32 */ 

DROP TABLE IF EXISTS `lucene_cmpgn_failover_dtl`;
CREATE TABLE `lucene_cmpgn_failover_dtl` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMARSYS_ACCOUNT` varchar(10) NOT NULL,
  `CMPGN_ID` varchar(100) NOT NULL,
  `CMPGN_INFO` varchar(1024) NOT NULL,
  `FAIL_TYPE` varchar(10) NOT NULL,
  `STATUS` varchar(10) NOT NULL,
  `FAIL_DESC` varchar(1024) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9301 DEFAULT CHARSET=utf8

DROP TABLE IF EXISTS `lucene_alert_info`;
CREATE TABLE `lucene_alert_info` (
  `ALERT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL_SUBJECT` varchar(100) NOT NULL,
  `TARGET_CODE` varchar(100) DEFAULT NULL,
  `ALERT_TYPE` varchar(100) NOT NULL,
  `TO_LIST` varchar(255) NOT NULL,
  `EMAIL_BODY` text NOT NULL,
  `ATTACHMENTS` varchar(255) DEFAULT NULL,
  `EMAIL_STATUS` char(255) NOT NULL,
  `JIRA_ID` varchar(100) DEFAULT NULL,
  `SEND_TIMES` int(11) NOT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT NULL,
  `UPDATED_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ALERT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8;