DROP TABLE IF EXISTS `zqdn_user_info`;
CREATE TABLE `zqdn_user_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPEN_ID` varchar(255) NOT NULL,
  `NICKNAME` varchar(255) NULL,
  `GENDER` TINYINT NOT NULL,
  `CITY` varchar(255) NULL,
  `PROVINCE` varchar(255) NULL,
  `COUNTRY` varchar(255) NULL,
  `AVATAR_URL` varchar(255) NULL,
  `UNION_ID` varchar(255) NULL,
  `RCMND_USR_ID` int(11) NULL,
  `CRE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPD_TS` timestamp NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `OPEN_ID` (`OPEN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `zqdn_game_score_instnc`;
CREATE TABLE `zqdn_game_score_instnc` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CMPGN_ID` SMALLINT NOT NULL,
  `OPEN_ID` varchar(255) NOT NULL,
  `SPEND_TIME` int(11) NOT NULL DEFAULT 0,
  `IS_FINISHED` TINYINT NOT NULL DEFAULT 0,
  `SCORE` int(11) NOT NULL DEFAULT 0,
  `CRE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8


DROP TABLE IF EXISTS `zqdn_game_lkp`;
CREATE TABLE `zqdn_game_lkp` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GAME_ID` SMALLINT NOT NULL,
  `GAME_NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

